name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.6.2+19

environment:
  sdk: ">=2.11.0 <=2.12.0"
  
dependencies:
  flutter:
    sdk: flutter
  flutter_material_color_picker: any
  draggable_scrollbar: any
  shared_preferences: any
  toggle_switch: any
  google_fonts: any
  firebase_core: any
  cloud_firestore: any
  wakelock: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any
  analyzer: any

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
