name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.6.2+19

environment:
  sdk: ">=2.10.0 <=2.12.0-27.0.dev"
  
dependencies:
  cloud_firestore: any
  draggable_scrollbar: any
  firebase_core: any
  flutter:
    sdk: flutter
  flutter_material_color_picker: any
  google_fonts: any
  shared_preferences: any
  toggle_switch: any
  wakelock: any

dev_dependencies:
  analyzer: any
  flutter_test:
    sdk: flutter
  pedantic: ^1.1.0-nullsafety

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
    - updating_songs.gif
