name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.6.5+23

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  cloud_firestore: ^4.7.1
  firebase_auth: ^4.6.1
  firebase_core: ^2.13.0
  shared_preferences: ^2.1.1
  toggle_switch: ^2.1.0
  wakelock: ^0.6.2
  draggable_scrollbar: ^0.1.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - updating_songs.gif
