name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.5.1+13

environment:
  sdk: ^2.8.1

dependencies:
  flutter:
    sdk: flutter
  draggable_scrollbar: any
  flutter_material_color_picker: any
  shared_preferences: any
  toggle_switch: any
  google_fonts: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
  uses-material-design: true

  assets:
    - assets/
    - google_fonts/