name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.6.3+21

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  cloud_firestore: any
  draggable_scrollbar: any
  firebase_auth: any
  firebase_core: any
  flutter:
    sdk: flutter
  flutter_material_color_picker: any
  shared_preferences: any
  toggle_switch: any
  wakelock: any

dev_dependencies:
  analyzer: any
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
  uses-material-design: true

  assets:
    - updating_songs.gif
