name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.6.4+22

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^2.2.0
  draggable_scrollbar: ^0.1.0
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  toggle_switch: ^0.1.9
  wakelock: ^0.5.2

dev_dependencies:
  analyzer: ^1.5.0
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - updating_songs.gif
