name: mladez_zpevnik
description: Bystricky mladezovy zpevnik

version: 1.4.1+11

environment:
  sdk: ^2.7.2

dependencies:
  flutter:
    sdk: flutter

  draggable_scrollbar: any
  flutter_spinkit: any
  flutter_material_color_picker: any
  pedantic: any
  shared_preferences: any
  popup_menu: any
  toggle_switch: any

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/