name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.6.3+21

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cloud_firestore: ^1.0.5
  draggable_scrollbar: ^0.1.0
  firebase_auth: ^1.1.0
  firebase_core: ^1.0.3
  flutter:
    sdk: flutter
  # flutter_material_color_picker: ^1.0.5
  shared_preferences: ^2.0.5
  toggle_switch: ^0.1.9
  wakelock: ^0.5.0+2

dev_dependencies:
  analyzer: ^1.4.0
  pedantic: ^1.11.0

flutter:
  uses-material-design: true

  assets:
    - updating_songs.gif
