name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.6.6+24

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.12.1
  firebase_auth: ^4.12.0
  firebase_core: ^2.20.0
  toggle_switch: ^2.1.0
  wakelock: ^0.6.2
  draggable_scrollbar: ^0.1.0
  objectbox: ^2.3.1
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
