name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 2.0.0+28

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.13.0
  firebase_auth: ^4.13.0
  firebase_core: ^2.22.0
  toggle_switch: ^2.1.0
  wakelock: ^0.6.2
  objectbox: ^2.3.1
  objectbox_flutter_libs: any
  get: ^4.6.6
  diacritic: ^0.1.4
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true

assets:
  - assets/
