name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 2.0.0+28

environment:
  sdk: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.5.0
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.0
  toggle_switch: ^2.1.0
  wakelock_plus: ^1.2.8
  objectbox: ^4.0.3
  objectbox_flutter_libs: any
  get: ^4.6.6
  diacritic: ^0.1.4
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true

assets:
  - assets/
