name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 1.5.3+15

environment:
  sdk: ^2.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_material_color_picker: any
  shared_preferences: any
  toggle_switch: any
  google_fonts: any
  universal_html: any
  firebase_core: any
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: any

flutter:
  uses-material-design: true

  assets:
    - google_fonts/
