name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 2.1.1+36

environment:
  sdk: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  toggle_switch: ^2.3.0
  wakelock_plus: ^1.2.11
  objectbox: ^4.2.0
  objectbox_flutter_libs: any
  get: ^4.7.2
  diacritic: ^0.1.6
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^5.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true
