name: mladez_zpevnik
description: Bystřický mládežový zpěvník

version: 2.2.0+41

environment:
  sdk: ">=3.8.0"

dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  toggle_switch: ^2.3.0
  wakelock_plus: ^1.2.11
  objectbox: ^4.2.0
  objectbox_flutter_libs: any
  get: ^4.7.2
  diacritic: ^0.1.6
  google_fonts: ^6.2.1
  auto_size_text: ^3.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  firebase_crashlytics: ^5.0.0
  firebase_analytics: ^12.0.0

  flutter_animate: ^4.5.0
  flutter_native_splash: ^2.4.6

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^6.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true


flutter_native_splash:
  color: "#4e4cbc"
  color_dark: "#1f2937"
  android_12:
    color: "#4e4cbc"
    color_dark: "#1f2937"
